name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: make
      - name: Test
        run: |
          ./test
          ./test-better
      - name: Bench
        run: |
          ./bench
          ./bench-better
